### ISSUE TITLE
Shadow border around Simdock in XFCE

### ISSUE THREAD

**Issue by probonopd** [onli/simdock#8]
`Simdock-3aab011-x86_64.AppImage` on `xubuntu-16.04.1-desktop-amd64.iso`:

![xfce](https://user-images.githubusercontent.com/2480569/44753666-60662980-ab0e-11e8-817c-2a65b9351695.gif)

**Comment by osbre** [comment]
some on cinammon

**Comment by onli** [comment]
Some context for this: The last thing `main` does is to call `xstuff_setDefaultWindowFlags(xid);`. Those flags are supposed to solve this. The function is https://github.com/onli/simdock/blob/88c08cfed4d6a51b968cda95e4c28f0cdb980c15/src/xstuff.cc#L49:L63

```
void
xstuff_setDefaultWindowFlags(Window winID) {
    // the wnck-functions don't work here reliably, at least on my system, so set the states with xcb
    xcb_ewmh_connection_t* ewmh_conn = xstuff_getConnection();
    xcb_ewmh_request_change_wm_desktop(ewmh_conn, 0 /* Screen */, winID, 0xFFFFFFFF, XCB_EWMH_CLIENT_SOURCE_TYPE_NORMAL);


    xcb_atom_t states[3] = {ewmh_conn->_NET_WM_STATE_SKIP_PAGER, ewmh_conn->_NET_WM_STATE_SKIP_TASKBAR,ewmh_conn->_NET_WM_STATE_ABOVE};
    xcb_atom_t types[1] = {ewmh_conn->_NET_WM_WINDOW_TYPE_DOCK};
    
    xcb_ewmh_set_wm_state(ewmh_conn, winID, 3, states);
    xcb_ewmh_set_wm_window_type(ewmh_conn, winID, 1, types);
    
    xcb_flush(ewmh_conn->connection);
    xstuff_closeConnection(ewmh_conn);
}
```

Note the `_NET_WM_WINDOW_TYPE_DOCK`. So either that code does not work, or that's the wrong window type for a dock, or the compositor is incorrectly not ignoring the window when painting shadows. Looking at an `xprop` output of the simdock window it seems the wm type declaration does not work and the issue is purely on simdocks side. I think the relevant output is:

    _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY

That should be `_NET_WM_WINDOW_TYPE_DOCK` (and that's something I'd need to double check), to give the compositor a chance to detect simdock as dock.

**Comment by onli** [comment]
It was a timing issue. Simdock tried to apply the flags before the X window was created, at least most of the time. Now it always gets the dock wmtype, if the shadow border remains that's on the compositor (but it works on my system).

Please re-open if the issue remains with the current AppImage.
